// <auto-generated />
using System;
using Frms.DataAccess.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frms.DataAccess.Migrations
{
    [DbContext(typeof(FrmsDbContext))]
    partial class FrmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuditLogId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("AuditLog", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_NewValueJson", "[NewValue] IS NULL OR ISJSON([NewValue])=1");

                            t.HasCheckConstraint("CK_AuditLog_OldValueJson", "[OldValue] IS NULL OR ISJSON([OldValue])=1");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Contract", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndMonth")
                        .HasColumnType("date");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartMonth")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<Guid>("StorageUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContractId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.HasIndex("StorageUnitId")
                        .IsUnique()
                        .HasFilter("[Status] = 'ACTIVE'");

                    b.ToTable("Contract", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contract_Months", "[EndMonth]>=[StartMonth]");

                            t.HasCheckConstraint("CK_Contract_Status", "[Status] IN ('ACTIVE','COMPLETED','TERMINATED')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.ContractExtension", b =>
                {
                    b.Property<Guid>("ContractExtensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AppliedMonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("NewEndMonth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("OldEndMonth")
                        .HasColumnType("date");

                    b.HasKey("ContractExtensionId");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractExtension", null, t =>
                        {
                            t.HasCheckConstraint("CK_ContractExtension_Months", "[NewEndMonth]>[OldEndMonth]");

                            t.HasCheckConstraint("CK_ContractExtension_Price", "[AppliedMonthlyPrice]>=0");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Cccd")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerId");

                    b.HasIndex("Cccd")
                        .IsUnique()
                        .HasFilter("[CCCD] IS NOT NULL");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.DamageRecord", b =>
                {
                    b.Property<Guid>("DamageRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("DamageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DamageTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("PENDING");

                    b.HasKey("DamageRecordId");

                    b.HasIndex("DamageTypeId");

                    b.HasIndex("InspectionId");

                    b.ToTable("DamageRecord", null, t =>
                        {
                            t.HasCheckConstraint("CK_DamageRecord_Amount", "[DamageAmount]>=0");

                            t.HasCheckConstraint("CK_DamageRecord_Status", "[Status] IN ('PENDING','APPROVED','REJECTED')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.DamageType", b =>
                {
                    b.Property<Guid>("DamageTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DefaultAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("DamageTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DamageType", null, t =>
                        {
                            t.HasCheckConstraint("CK_DamageType_DefaultAmount", "[DefaultAmount] IS NULL OR [DefaultAmount]>=0");

                            t.HasCheckConstraint("CK_DamageType_Status", "[Status] IN ('ACTIVE','INACTIVE')");
                        });

                    b.HasData(
                        new
                        {
                            DamageTypeId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Name = "LOCK_DAMAGE",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            DamageTypeId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Name = "DOOR_DAMAGE",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            DamageTypeId = new Guid("30000000-0000-0000-0000-000000000003"),
                            Name = "WALL_DAMAGE",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            DamageTypeId = new Guid("30000000-0000-0000-0000-000000000004"),
                            Name = "FLOOR_DAMAGE",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            DamageTypeId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Name = "WATER_DAMAGE",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            DamageTypeId = new Guid("30000000-0000-0000-0000-000000000006"),
                            Name = "OTHER",
                            Status = "ACTIVE"
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.DepositSettlement", b =>
                {
                    b.Property<Guid>("DepositSettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdditionalAmountDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("PENDING");

                    b.Property<decimal>("TotalDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DepositSettlementId");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("DepositSettlement", null, t =>
                        {
                            t.HasCheckConstraint("CK_DepositSettlement_Amounts", "[TotalDeduction]>=0 AND [RefundAmount]>=0 AND [AdditionalAmountDue]>=0");

                            t.HasCheckConstraint("CK_DepositSettlement_Status", "[Status] IN ('PENDING','FINALIZED')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Discount", b =>
                {
                    b.Property<Guid>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("DiscountId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Discount", null, t =>
                        {
                            t.HasCheckConstraint("CK_Discount_Percentage", "[Percentage] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Discount_Status", "[Status] IN ('ACTIVE','INACTIVE')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.ExtraFee", b =>
                {
                    b.Property<Guid>("ExtraFeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("ExtraFeeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ExtraFeeId");

                    b.HasIndex("ExtraFeeTypeId");

                    b.HasIndex("InspectionId");

                    b.ToTable("ExtraFee", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExtraFee_Amount", "[Amount]>=0");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.ExtraFeeType", b =>
                {
                    b.Property<Guid>("ExtraFeeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DefaultAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("ExtraFeeTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ExtraFeeType", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExtraFeeType_DefaultAmount", "[DefaultAmount]>=0");

                            t.HasCheckConstraint("CK_ExtraFeeType_Name", "[Name] IN ('KEY_REPLACEMENT','ACCESS_CARD_REPLACEMENT','LOCK_REPLACEMENT','CLEANING_FEE','OTHER')");

                            t.HasCheckConstraint("CK_ExtraFeeType_Status", "[Status] IN ('ACTIVE','INACTIVE')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Facility", b =>
                {
                    b.Property<Guid>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("INACTIVE");

                    b.HasKey("FacilityId");

                    b.ToTable("Facility", null, t =>
                        {
                            t.HasCheckConstraint("CK_Facility_Status", "[Status] IN ('ACTIVE','INACTIVE')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Inspection", b =>
                {
                    b.Property<Guid>("InspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ConditionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("PENDING");

                    b.Property<Guid>("StorageUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InspectionId");

                    b.HasIndex("ContractId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StorageUnitId");

                    b.HasIndex("VisitId");

                    b.ToTable("Inspection", null, t =>
                        {
                            t.HasCheckConstraint("CK_Inspection_Status", "[Status] IN ('PENDING','IN_PROGRESS','COMPLETED')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.InspectionEvidence", b =>
                {
                    b.Property<Guid>("InspectionEvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InspectionEvidenceId");

                    b.HasIndex("InspectionId");

                    b.ToTable("InspectionEvidence", null, t =>
                        {
                            t.HasCheckConstraint("CK_InspectionEvidence_Type", "[EvidenceType] IN ('IMAGE','VIDEO','DOCUMENT')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("BillingMonth")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid?>("DiscountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("UNPAID");

                    b.HasKey("InvoiceId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("EntityId")
                        .IsUnique()
                        .HasFilter("[InvoiceType] = 'DEPOSIT'");

                    b.HasIndex("EntityId", "BillingMonth")
                        .IsUnique()
                        .HasFilter("[InvoiceType] = 'RENTAL_FEE'");

                    b.ToTable("Invoice", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invoice_Amounts", "[BaseAmount]>=0 AND [DiscountAmount]>=0 AND [AmountDue]>=0");

                            t.HasCheckConstraint("CK_Invoice_BillingMonth", "([InvoiceType]='DEPOSIT' AND [BillingMonth] IS NULL) OR ([InvoiceType]='RENTAL_FEE' AND [BillingMonth] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Invoice_Status", "[Status] IN ('UNPAID','PAID','OVERDUE','CANCELLED')");

                            t.HasCheckConstraint("CK_Invoice_Type", "[InvoiceType] IN ('DEPOSIT','RENTAL_FEE')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.LateFee", b =>
                {
                    b.Property<Guid>("LateFeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OverdueDays")
                        .HasColumnType("int");

                    b.HasKey("LateFeeId");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("LateFee", null, t =>
                        {
                            t.HasCheckConstraint("CK_LateFee_Amount", "[Amount]>=0");

                            t.HasCheckConstraint("CK_LateFee_Days", "[OverdueDays]>=1");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.LoginHistory", b =>
                {
                    b.Property<Guid>("LoginHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("LoginAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginHistoryId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("LoginHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_LoginHistory_Status", "[Status] IN ('SUCCESS','FAILED')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("NotificationLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("PENDING");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationLogId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("NotificationLog", null, t =>
                        {
                            t.HasCheckConstraint("CK_NotificationLog_SentAt", "([Status]='PENDING' AND [SentAt] IS NULL) OR ([Status]='SENT' AND [SentAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotificationLog_Status", "[Status] IN ('PENDING','SENT')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("varchar(150)");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TransactionCode")
                        .IsUnique()
                        .HasFilter("[TransactionCode] IS NOT NULL");

                    b.ToTable("Payment", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Amount", "[Amount]>0");

                            t.HasCheckConstraint("CK_Payment_Method", "[PaymentMethod]='MOMO'");

                            t.HasCheckConstraint("CK_Payment_PaidAt", "([Status]='SUCCESS' AND [PaidAt] IS NOT NULL) OR ([Status]<>'SUCCESS' AND [PaidAt] IS NULL)");

                            t.HasCheckConstraint("CK_Payment_Status", "[Status] IN ('PENDING','SUCCESS','FAILED')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Policy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DepositTimeoutHours")
                        .HasColumnType("int");

                    b.Property<int>("EarlyReturnWaiveFeeUntilDay")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("LateFeeDivisorDays")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyPaymentDueDay")
                        .HasColumnType("int");

                    b.Property<int>("OverdueStartDay")
                        .HasColumnType("int");

                    b.Property<int>("ReservationVisitEndDay")
                        .HasColumnType("int");

                    b.Property<int>("ReservationVisitStartDay")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasFilter("[Status] = 'ACTIVE'");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("Policy", null, t =>
                        {
                            t.HasCheckConstraint("CK_Policy_Days", "[DepositTimeoutHours]>0 AND [ReservationVisitStartDay] BETWEEN 1 AND 31 AND [ReservationVisitEndDay] BETWEEN 1 AND 31 AND [ReservationVisitStartDay] <= [ReservationVisitEndDay] AND [MonthlyPaymentDueDay] BETWEEN 1 AND 31 AND [OverdueStartDay] BETWEEN 1 AND 31 AND [LateFeeDivisorDays]>0 AND [EarlyReturnWaiveFeeUntilDay] BETWEEN 1 AND 31");

                            t.HasCheckConstraint("CK_Policy_Status", "[Status] IN ('ACTIVE','INACTIVE')");
                        });

                    b.HasData(
                        new
                        {
                            PolicyId = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepositTimeoutHours = 1,
                            EarlyReturnWaiveFeeUntilDay = 5,
                            EffectiveFrom = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            LateFeeDivisorDays = 31,
                            MonthlyPaymentDueDay = 5,
                            OverdueStartDay = 6,
                            ReservationVisitEndDay = 5,
                            ReservationVisitStartDay = 1,
                            Status = "ACTIVE",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("EndMonth")
                        .HasColumnType("date");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LockedRentalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartMonth")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("PENDING_DEPOSIT");

                    b.Property<Guid>("UnitTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("Reservation", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reservation_Amounts", "[LockedRentalPrice]>=0 AND [DepositAmount]>=0");

                            t.HasCheckConstraint("CK_Reservation_Months", "[EndMonth]>=[StartMonth]");

                            t.HasCheckConstraint("CK_Reservation_Status", "[Status] IN ('PENDING_DEPOSIT','CONFIRMED','COMPLETED','CANCELLED')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.StorageUnit", b =>
                {
                    b.Property<Guid>("StorageUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocationInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("AVAILABLE");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UnitTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StorageUnitId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("StorageUnit", null, t =>
                        {
                            t.HasCheckConstraint("CK_StorageUnit_Status", "[Status] IN ('AVAILABLE','IN_USE','INSPECTION','MAINTENANCE')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("SupportTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ResultNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("OPEN");

                    b.HasKey("SupportTicketId");

                    b.HasIndex("AssignedEmployeeId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CustomerId");

                    b.ToTable("SupportTicket", null, t =>
                        {
                            t.HasCheckConstraint("CK_SupportTicket_Category", "[Category] IN ('UNIT_ISSUE','LOCK_KEY_ISSUE','ACCESS_CARD_CODE_ISSUE','PAYMENT_ISSUE','STORED_ITEM_ISSUE','DAMAGE_ISSUE','OTHER')");

                            t.HasCheckConstraint("CK_SupportTicket_Status", "[Status] IN ('OPEN','IN_PROGRESS','COMPLETED','CANCELLED')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.UnitType", b =>
                {
                    b.Property<Guid>("UnitTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("RentalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("UnitTypeId");

                    b.ToTable("UnitType", null, t =>
                        {
                            t.HasCheckConstraint("CK_UnitType_Mode", "[Mode] IN ('PUBLIC','PRIVATE')");

                            t.HasCheckConstraint("CK_UnitType_RentalPrice", "[RentalPrice]>=0");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("UserAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("UserAccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("UserAccount", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserAccount_Status", "[Status] IN ('ACTIVE','INACTIVE')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("UserRole", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserRole_RoleName", "[RoleName] IN ('CUSTOMER','FACILITY_STAFF','FACILITY_MANAGER','BUSINESS_OPERATIONS_MANAGER','SYSTEM_ADMINISTRATOR')");
                        });

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            RoleName = "CUSTOMER"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            RoleName = "FACILITY_STAFF"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            RoleName = "FACILITY_MANAGER"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000004"),
                            RoleName = "BUSINESS_OPERATIONS_MANAGER"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000005"),
                            RoleName = "SYSTEM_ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Visit", b =>
                {
                    b.Property<Guid>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("SCHEDULED");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("VisitId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Visit", null, t =>
                        {
                            t.HasCheckConstraint("CK_Visit_Status", "[Status] IN ('SCHEDULED','CHECKED_IN','CHECKED_OUT','CANCELLED')");

                            t.HasCheckConstraint("CK_Visit_Type", "[VisitType] IN ('RESERVATION','ACCESS','RETURN')");
                        });
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.AuditLog", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Contract", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Discount", null)
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Reservation", null)
                        .WithOne()
                        .HasForeignKey("Frms.DataAccess.Persistence.Entities.Contract", "ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.StorageUnit", null)
                        .WithMany()
                        .HasForeignKey("StorageUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.ContractExtension", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Customer", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Frms.DataAccess.Persistence.Entities.Customer", "UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.DamageRecord", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.DamageType", null)
                        .WithMany()
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.DepositSettlement", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Contract", null)
                        .WithOne()
                        .HasForeignKey("Frms.DataAccess.Persistence.Entities.DepositSettlement", "ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Discount", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Employee", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Frms.DataAccess.Persistence.Entities.UserAccount", null)
                        .WithOne()
                        .HasForeignKey("Frms.DataAccess.Persistence.Entities.Employee", "UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.ExtraFee", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.ExtraFeeType", null)
                        .WithMany()
                        .HasForeignKey("ExtraFeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Inspection", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Frms.DataAccess.Persistence.Entities.StorageUnit", null)
                        .WithMany()
                        .HasForeignKey("StorageUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.InspectionEvidence", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Invoice", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Discount", null)
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.LateFee", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Invoice", null)
                        .WithOne()
                        .HasForeignKey("Frms.DataAccess.Persistence.Entities.LateFee", "InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.LoginHistory", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.NotificationLog", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Payment", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Reservation", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.UnitType", null)
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.StorageUnit", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.UnitType", null)
                        .WithMany()
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.SupportTicket", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("AssignedEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frms.DataAccess.Persistence.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.UserAccount", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Frms.DataAccess.Persistence.Entities.Visit", b =>
                {
                    b.HasOne("Frms.DataAccess.Persistence.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
