using Frms.DataAccess.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Frms.DataAccess.Persistence.Configurations;

internal static class FrmsModelConfiguration
{
    private const string Money = "decimal(18,2)";
    private const string Timestamp = "datetime2(3)";

    public static void ApplyFrmsConfiguration(this ModelBuilder m)
    {
        ConfigureMasters(m);
        ConfigureAccounts(m);
        ConfigureRental(m);
        ConfigureInspectionAndSupport(m);
        ConfigureOperationalLogs(m);
        ConfigureSeed(m);
    }

    private static void ConfigureMasters(ModelBuilder m)
    {
        m.Entity<UserRole>(e => { e.ToTable("UserRole", t => t.HasCheckConstraint("CK_UserRole_RoleName", "[RoleName] IN ('CUSTOMER','FACILITY_STAFF','FACILITY_MANAGER','BUSINESS_OPERATIONS_MANAGER','SYSTEM_ADMINISTRATOR')")); e.HasKey(x => x.RoleId); Code(e.Property(x => x.RoleName)); e.HasIndex(x => x.RoleName).IsUnique(); e.Property(x => x.Description).HasMaxLength(1000); });
        m.Entity<Policy>(e => { e.ToTable("Policy", t => { t.HasCheckConstraint("CK_Policy_Status", "[Status] IN ('ACTIVE','INACTIVE')"); t.HasCheckConstraint("CK_Policy_Days", "[DepositTimeoutHours]>0 AND [ReservationVisitStartDay] BETWEEN 1 AND 31 AND [ReservationVisitEndDay] BETWEEN 1 AND 31 AND [ReservationVisitStartDay] <= [ReservationVisitEndDay] AND [MonthlyPaymentDueDay] BETWEEN 1 AND 31 AND [OverdueStartDay] BETWEEN 1 AND 31 AND [LateFeeDivisorDays]>0 AND [EarlyReturnWaiveFeeUntilDay] BETWEEN 1 AND 31"); }); e.HasKey(x => x.PolicyId); e.HasIndex(x => x.Version).IsUnique(); e.HasIndex(x => x.Status).IsUnique().HasFilter("[Status] = 'ACTIVE'"); Code(e.Property(x => x.Status)).HasDefaultValue("ACTIVE"); Utc(e.Property(x => x.EffectiveFrom)); Utc(e.Property(x => x.EffectiveTo)); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); });
        m.Entity<Facility>(e => { e.ToTable("Facility", t => t.HasCheckConstraint("CK_Facility_Status", "[Status] IN ('ACTIVE','INACTIVE')")); e.HasKey(x => x.FacilityId); Name(e.Property(x => x.Name)); e.Property(x => x.Address).HasMaxLength(1000); e.Property(x => x.ContactInfo).HasMaxLength(1000); e.Property(x => x.Description).HasMaxLength(1000); Code(e.Property(x => x.Status)).HasDefaultValue("INACTIVE"); });
        m.Entity<UnitType>(e => { e.ToTable("UnitType", t => { t.UseSqlOutputClause(false); t.HasCheckConstraint("CK_UnitType_Mode", "[Mode] IN ('PUBLIC','PRIVATE')"); t.HasCheckConstraint("CK_UnitType_RentalPrice", "[RentalPrice]>=0"); }); e.HasKey(x => x.UnitTypeId); Name(e.Property(x => x.Name)); Code(e.Property(x => x.Mode)); e.Property(x => x.Size).HasMaxLength(150); Amount(e.Property(x => x.RentalPrice)); e.Property(x => x.Description).HasMaxLength(1000); });
        m.Entity<DamageType>(e => { e.ToTable("DamageType", t => { t.HasCheckConstraint("CK_DamageType_Status", "[Status] IN ('ACTIVE','INACTIVE')"); t.HasCheckConstraint("CK_DamageType_DefaultAmount", "[DefaultAmount] IS NULL OR [DefaultAmount]>=0"); }); e.HasKey(x => x.DamageTypeId); Name(e.Property(x => x.Name)); e.HasIndex(x => x.Name).IsUnique(); Amount(e.Property(x => x.DefaultAmount)); Code(e.Property(x => x.Status)).HasDefaultValue("ACTIVE"); });
        m.Entity<ExtraFeeType>(e => { e.ToTable("ExtraFeeType", t => { t.HasCheckConstraint("CK_ExtraFeeType_Name", "[Name] IN ('KEY_REPLACEMENT','ACCESS_CARD_REPLACEMENT','LOCK_REPLACEMENT','CLEANING_FEE','OTHER')"); t.HasCheckConstraint("CK_ExtraFeeType_Status", "[Status] IN ('ACTIVE','INACTIVE')"); t.HasCheckConstraint("CK_ExtraFeeType_DefaultAmount", "[DefaultAmount]>=0"); }); e.HasKey(x => x.ExtraFeeTypeId); Code(e.Property(x => x.Name)); e.HasIndex(x => x.Name).IsUnique(); Amount(e.Property(x => x.DefaultAmount)); Code(e.Property(x => x.Status)).HasDefaultValue("ACTIVE"); });
    }

    private static void ConfigureAccounts(ModelBuilder m)
    {
        m.Entity<UserAccount>(e => { e.ToTable("UserAccount", t => { t.HasCheckConstraint("CK_UserAccount_Status", "[Status] IN ('ACTIVE','INACTIVE')"); t.UseSqlOutputClause(false); }); e.HasKey(x => x.UserAccountId); e.HasOne<UserRole>().WithMany().HasForeignKey(x => x.RoleId).OnDelete(DeleteBehavior.Restrict); e.Property(x => x.Email).HasColumnType("varchar(254)"); e.Property(x => x.PhoneNumber).HasColumnType("varchar(30)"); e.Property(x => x.PasswordHash).HasColumnType("varchar(255)"); Code(e.Property(x => x.Status)).HasDefaultValue("ACTIVE"); e.HasIndex(x => x.Email).IsUnique(); e.HasIndex(x => x.PhoneNumber).IsUnique(); Utc(e.Property(x => x.EmailVerifiedAt)); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); });
        m.Entity<Customer>(e => { e.ToTable("Customer", t =>{ t.UseSqlOutputClause(false);} ); e.HasKey(x => x.CustomerId); e.HasOne<UserAccount>().WithOne().HasForeignKey<Customer>(x => x.UserAccountId).OnDelete(DeleteBehavior.Restrict); Name(e.Property(x => x.FullName)); e.Property(x => x.Address).HasMaxLength(1000); e.Property(x => x.Cccd).HasColumnName("CCCD").HasColumnType("varchar(20)"); e.HasIndex(x => x.Cccd).IsUnique().HasFilter("[CCCD] IS NOT NULL"); });
        m.Entity<Employee>(e => { e.ToTable("Employee", t =>{ t.UseSqlOutputClause(false);} ); e.HasKey(x => x.EmployeeId); e.HasOne<UserAccount>().WithOne().HasForeignKey<Employee>(x => x.UserAccountId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Facility>().WithMany().HasForeignKey(x => x.FacilityId).OnDelete(DeleteBehavior.Restrict); Name(e.Property(x => x.FullName)); });
    }

    private static void ConfigureRental(ModelBuilder m)
    {
        m.Entity<StorageUnit>(e => { e.ToTable("StorageUnit", t => { t.HasCheckConstraint("CK_StorageUnit_Status", "[Status] IN ('AVAILABLE','IN_USE','INSPECTION','MAINTENANCE')"); t.UseSqlOutputClause(false); }); e.HasKey(x => x.StorageUnitId); e.HasOne<Facility>().WithMany().HasForeignKey(x => x.FacilityId).OnDelete(DeleteBehavior.Restrict); e.HasOne<UnitType>().WithMany().HasForeignKey(x => x.UnitTypeId).OnDelete(DeleteBehavior.Restrict); e.Property(x => x.UnitCode).HasColumnType("varchar(50)"); e.Property(x => x.LocationInfo).HasMaxLength(1000); Code(e.Property(x => x.Status)).HasDefaultValue("AVAILABLE"); });
        m.Entity<Reservation>(e => { e.ToTable("Reservation", t => { t.HasCheckConstraint("CK_Reservation_Status", "[Status] IN ('PENDING_DEPOSIT','CONFIRMED','COMPLETED','CANCELLED')"); t.HasCheckConstraint("CK_Reservation_Months", "[EndMonth]>=[StartMonth]"); t.HasCheckConstraint("CK_Reservation_Amounts", "[LockedRentalPrice]>=0 AND [DepositAmount]>=0"); }); e.HasKey(x => x.ReservationId); e.HasOne<Customer>().WithMany().HasForeignKey(x => x.CustomerId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Facility>().WithMany().HasForeignKey(x => x.FacilityId).OnDelete(DeleteBehavior.Restrict); e.HasOne<UnitType>().WithMany().HasForeignKey(x => x.UnitTypeId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Policy>().WithMany().HasForeignKey(x => x.PolicyId).OnDelete(DeleteBehavior.Restrict); Amount(e.Property(x => x.LockedRentalPrice)); Amount(e.Property(x => x.DepositAmount)); Code(e.Property(x => x.Status)).HasDefaultValue("PENDING_DEPOSIT"); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); });
        m.Entity<Visit>(e => { e.ToTable("Visit", t => { t.HasCheckConstraint("CK_Visit_Type", "[VisitType] IN ('RESERVATION','ACCESS','RETURN')"); t.HasCheckConstraint("CK_Visit_Status", "[Status] IN ('SCHEDULED','CHECKED_IN','CHECKED_OUT','CANCELLED')"); }); e.HasKey(x => x.VisitId); e.HasOne<Employee>().WithMany().HasForeignKey(x => x.EmployeeId).OnDelete(DeleteBehavior.Restrict); Code(e.Property(x => x.VisitType)); Code(e.Property(x => x.Status)).HasDefaultValue("SCHEDULED"); Utc(e.Property(x => x.ActualReturnDate)); });
        m.Entity<Discount>(e => { e.ToTable("Discount", t => { t.HasCheckConstraint("CK_Discount_Percentage", "[Percentage] BETWEEN 0 AND 100"); t.HasCheckConstraint("CK_Discount_Status", "[Status] IN ('ACTIVE','INACTIVE')"); }); e.HasKey(x => x.DiscountId); e.HasOne<Customer>().WithMany().HasForeignKey(x => x.CustomerId).OnDelete(DeleteBehavior.Restrict); Name(e.Property(x => x.Name)); e.Property(x => x.Percentage).HasColumnType("decimal(5,2)"); Code(e.Property(x => x.Status)).HasDefaultValue("ACTIVE"); Utc(e.Property(x => x.EffectiveFrom)); Utc(e.Property(x => x.EffectiveTo)); });
        m.Entity<Contract>(e => { e.ToTable("Contract", t => { t.HasCheckConstraint("CK_Contract_Status", "[Status] IN ('ACTIVE','COMPLETED','TERMINATED')"); t.HasCheckConstraint("CK_Contract_Months", "[EndMonth]>=[StartMonth]"); }); e.HasKey(x => x.ContractId); e.HasIndex(x => x.ReservationId).IsUnique(); e.HasIndex(x => x.StorageUnitId).IsUnique().HasFilter("[Status] = 'ACTIVE'"); e.HasOne<Reservation>().WithOne().HasForeignKey<Contract>(x => x.ReservationId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Customer>().WithMany().HasForeignKey(x => x.CustomerId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Facility>().WithMany().HasForeignKey(x => x.FacilityId).OnDelete(DeleteBehavior.Restrict); e.HasOne<StorageUnit>().WithMany().HasForeignKey(x => x.StorageUnitId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Policy>().WithMany().HasForeignKey(x => x.PolicyId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Discount>().WithMany().HasForeignKey(x => x.DiscountId).OnDelete(DeleteBehavior.Restrict); Code(e.Property(x => x.Status)).HasDefaultValue("ACTIVE"); });
        m.Entity<ContractExtension>(e => { e.ToTable("ContractExtension", t => { t.HasCheckConstraint("CK_ContractExtension_Months", "[NewEndMonth]>[OldEndMonth]"); t.HasCheckConstraint("CK_ContractExtension_Price", "[AppliedMonthlyPrice]>=0"); }); e.HasKey(x => x.ContractExtensionId); e.HasOne<Contract>().WithMany().HasForeignKey(x => x.ContractId).OnDelete(DeleteBehavior.Restrict); Amount(e.Property(x => x.AppliedMonthlyPrice)); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); });
        m.Entity<Invoice>(e => { e.ToTable("Invoice", t => { t.HasCheckConstraint("CK_Invoice_Type", "[InvoiceType] IN ('DEPOSIT','RENTAL_FEE')"); t.HasCheckConstraint("CK_Invoice_Status", "[Status] IN ('UNPAID','PAID','OVERDUE','CANCELLED')"); t.HasCheckConstraint("CK_Invoice_Amounts", "[BaseAmount]>=0 AND [DiscountAmount]>=0 AND [AmountDue]>=0"); t.HasCheckConstraint("CK_Invoice_BillingMonth", "([InvoiceType]='DEPOSIT' AND [BillingMonth] IS NULL) OR ([InvoiceType]='RENTAL_FEE' AND [BillingMonth] IS NOT NULL)"); }); e.HasKey(x => x.InvoiceId); e.HasOne<Discount>().WithMany().HasForeignKey(x => x.DiscountId).OnDelete(DeleteBehavior.Restrict); Code(e.Property(x => x.InvoiceType)); Code(e.Property(x => x.Status)).HasDefaultValue("UNPAID"); Amount(e.Property(x => x.BaseAmount)); Amount(e.Property(x => x.DiscountAmount)).HasDefaultValue(0m); Amount(e.Property(x => x.AmountDue)); Utc(e.Property(x => x.DueDate)); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); e.HasIndex(x => x.EntityId).IsUnique().HasFilter("[InvoiceType] = 'DEPOSIT'"); e.HasIndex(x => new { x.EntityId, x.BillingMonth }).IsUnique().HasFilter("[InvoiceType] = 'RENTAL_FEE'"); });
        m.Entity<Payment>(e => { e.ToTable("Payment", t => { t.HasCheckConstraint("CK_Payment_Method", "[PaymentMethod]='MOMO'"); t.HasCheckConstraint("CK_Payment_Status", "[Status] IN ('PENDING','SUCCESS','FAILED')"); t.HasCheckConstraint("CK_Payment_Amount", "[Amount]>0"); t.HasCheckConstraint("CK_Payment_PaidAt", "([Status]='SUCCESS' AND [PaidAt] IS NOT NULL) OR ([Status]<>'SUCCESS' AND [PaidAt] IS NULL)"); }); e.HasKey(x => x.PaymentId); e.HasOne<Invoice>().WithMany().HasForeignKey(x => x.InvoiceId).OnDelete(DeleteBehavior.Restrict); Amount(e.Property(x => x.Amount)); Code(e.Property(x => x.PaymentMethod)); Code(e.Property(x => x.Status)).HasDefaultValue("PENDING"); e.Property(x => x.TransactionCode).HasColumnType("varchar(150)"); e.HasIndex(x => x.TransactionCode).IsUnique().HasFilter("[TransactionCode] IS NOT NULL"); Utc(e.Property(x => x.PaidAt)); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); });
        m.Entity<LateFee>(e => { e.ToTable("LateFee", t => { t.HasCheckConstraint("CK_LateFee_Days", "[OverdueDays]>=1"); t.HasCheckConstraint("CK_LateFee_Amount", "[Amount]>=0"); }); e.HasKey(x => x.LateFeeId); e.HasOne<Invoice>().WithOne().HasForeignKey<LateFee>(x => x.InvoiceId).OnDelete(DeleteBehavior.Restrict); Amount(e.Property(x => x.Amount)); Utc(e.Property(x => x.CalculatedAt)); });
    }

    private static void ConfigureInspectionAndSupport(ModelBuilder m)
    {
        m.Entity<SupportTicket>(e => { e.ToTable("SupportTicket", t => { t.HasCheckConstraint("CK_SupportTicket_Category", "[Category] IN ('UNIT_ISSUE','LOCK_KEY_ISSUE','ACCESS_CARD_CODE_ISSUE','PAYMENT_ISSUE','STORED_ITEM_ISSUE','DAMAGE_ISSUE','OTHER')"); t.HasCheckConstraint("CK_SupportTicket_Status", "[Status] IN ('OPEN','IN_PROGRESS','COMPLETED','CANCELLED')"); }); e.HasKey(x => x.SupportTicketId); e.HasOne<Contract>().WithMany().HasForeignKey(x => x.ContractId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Customer>().WithMany().HasForeignKey(x => x.CustomerId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Employee>().WithMany().HasForeignKey(x => x.AssignedEmployeeId).OnDelete(DeleteBehavior.Restrict); Code(e.Property(x => x.Category)); Code(e.Property(x => x.Status)).HasDefaultValue("OPEN"); e.Property(x => x.Description).HasMaxLength(1000); e.Property(x => x.ResultNote).HasMaxLength(1000); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); Utc(e.Property(x => x.CompletedAt)); });
        m.Entity<Inspection>(e => { e.ToTable("Inspection", t => t.HasCheckConstraint("CK_Inspection_Status", "[Status] IN ('PENDING','IN_PROGRESS','COMPLETED')")); e.HasKey(x => x.InspectionId); e.HasOne<Contract>().WithMany().HasForeignKey(x => x.ContractId).OnDelete(DeleteBehavior.Restrict); e.HasOne<StorageUnit>().WithMany().HasForeignKey(x => x.StorageUnitId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Visit>().WithMany().HasForeignKey(x => x.VisitId).OnDelete(DeleteBehavior.Restrict); e.HasOne<Employee>().WithMany().HasForeignKey(x => x.EmployeeId).OnDelete(DeleteBehavior.Restrict); Code(e.Property(x => x.Status)).HasDefaultValue("PENDING"); e.Property(x => x.ConditionNote).HasMaxLength(1000); Utc(e.Property(x => x.CompletedAt)); });
        m.Entity<DamageRecord>(e => { e.ToTable("DamageRecord", t => { t.HasCheckConstraint("CK_DamageRecord_Status", "[Status] IN ('PENDING','APPROVED','REJECTED')"); t.HasCheckConstraint("CK_DamageRecord_Amount", "[DamageAmount]>=0"); }); e.HasKey(x => x.DamageRecordId); e.HasOne<Inspection>().WithMany().HasForeignKey(x => x.InspectionId).OnDelete(DeleteBehavior.Restrict); e.HasOne<DamageType>().WithMany().HasForeignKey(x => x.DamageTypeId).OnDelete(DeleteBehavior.Restrict); Amount(e.Property(x => x.DamageAmount)); e.Property(x => x.Note).HasMaxLength(1000); Code(e.Property(x => x.Status)).HasDefaultValue("PENDING"); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); });
        m.Entity<InspectionEvidence>(e => { e.ToTable("InspectionEvidence", t => t.HasCheckConstraint("CK_InspectionEvidence_Type", "[EvidenceType] IN ('IMAGE','VIDEO','DOCUMENT')")); e.HasKey(x => x.InspectionEvidenceId); e.HasOne<Inspection>().WithMany().HasForeignKey(x => x.InspectionId).OnDelete(DeleteBehavior.Restrict); e.Property(x => x.FileData).HasColumnType("varbinary(max)"); Code(e.Property(x => x.EvidenceType)); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); });
        m.Entity<ExtraFee>(e => { e.ToTable("ExtraFee", t => t.HasCheckConstraint("CK_ExtraFee_Amount", "[Amount]>=0")); e.HasKey(x => x.ExtraFeeId); e.HasOne<Inspection>().WithMany().HasForeignKey(x => x.InspectionId).OnDelete(DeleteBehavior.Restrict); e.HasOne<ExtraFeeType>().WithMany().HasForeignKey(x => x.ExtraFeeTypeId).OnDelete(DeleteBehavior.Restrict); Amount(e.Property(x => x.Amount)); e.Property(x => x.Reason).HasMaxLength(1000); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); });
        m.Entity<DepositSettlement>(e => { e.ToTable("DepositSettlement", t => { t.HasCheckConstraint("CK_DepositSettlement_Status", "[Status] IN ('PENDING','FINALIZED')"); t.HasCheckConstraint("CK_DepositSettlement_Amounts", "[TotalDeduction]>=0 AND [RefundAmount]>=0 AND [AdditionalAmountDue]>=0"); }); e.HasKey(x => x.DepositSettlementId); e.HasOne<Contract>().WithOne().HasForeignKey<DepositSettlement>(x => x.ContractId).OnDelete(DeleteBehavior.Restrict); Amount(e.Property(x => x.TotalDeduction)); Amount(e.Property(x => x.RefundAmount)); Amount(e.Property(x => x.AdditionalAmountDue)); Code(e.Property(x => x.Status)).HasDefaultValue("PENDING"); Utc(e.Property(x => x.CalculatedAt)); });
    }

    private static void ConfigureOperationalLogs(ModelBuilder m)
    {
        m.Entity<LoginHistory>(e => { e.ToTable("LoginHistory", t => t.HasCheckConstraint("CK_LoginHistory_Status", "[Status] IN ('SUCCESS','FAILED')")); e.HasKey(x => x.LoginHistoryId); e.HasOne<UserAccount>().WithMany().HasForeignKey(x => x.UserAccountId).OnDelete(DeleteBehavior.Restrict); e.Property(x => x.IpAddress).HasColumnType("varchar(45)"); e.Property(x => x.DeviceInfo).HasMaxLength(1000); Code(e.Property(x => x.Status)); Utc(e.Property(x => x.LoginAt)).HasDefaultValueSql("SYSUTCDATETIME()"); });
        m.Entity<AuditLog>(e => { e.ToTable("AuditLog", t => { t.HasCheckConstraint("CK_AuditLog_OldValueJson", "[OldValue] IS NULL OR ISJSON([OldValue])=1"); t.HasCheckConstraint("CK_AuditLog_NewValueJson", "[NewValue] IS NULL OR ISJSON([NewValue])=1"); }); e.HasKey(x => x.AuditLogId); e.HasOne<UserAccount>().WithMany().HasForeignKey(x => x.UserAccountId).OnDelete(DeleteBehavior.Restrict); e.Property(x => x.Action).HasColumnType("varchar(150)"); e.Property(x => x.EntityType).HasColumnType("varchar(150)"); e.Property(x => x.OldValue).HasColumnType("nvarchar(max)"); e.Property(x => x.NewValue).HasColumnType("nvarchar(max)"); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); });
        m.Entity<NotificationLog>(e => { e.ToTable("NotificationLog", t => { t.HasCheckConstraint("CK_NotificationLog_Status", "[Status] IN ('PENDING','SENT')"); t.HasCheckConstraint("CK_NotificationLog_SentAt", "([Status]='PENDING' AND [SentAt] IS NULL) OR ([Status]='SENT' AND [SentAt] IS NOT NULL)"); }); e.HasKey(x => x.NotificationLogId); e.HasOne<UserAccount>().WithMany().HasForeignKey(x => x.UserAccountId).OnDelete(DeleteBehavior.Restrict); Code(e.Property(x => x.NotificationType)); e.Property(x => x.Content).HasMaxLength(1000); Code(e.Property(x => x.Status)).HasDefaultValue("PENDING"); Utc(e.Property(x => x.SentAt)); Utc(e.Property(x => x.CreatedAt)).HasDefaultValueSql("SYSUTCDATETIME()"); });
    }

    private static void ConfigureSeed(ModelBuilder m)
    {
        m.Entity<UserRole>().HasData(
            new UserRole { RoleId = SeedIds.CustomerRole, RoleName = "CUSTOMER" },
            new UserRole { RoleId = SeedIds.FacilityStaffRole, RoleName = "FACILITY_STAFF" },
            new UserRole { RoleId = SeedIds.FacilityManagerRole, RoleName = "FACILITY_MANAGER" },
            new UserRole { RoleId = SeedIds.BusinessOperationsManagerRole, RoleName = "BUSINESS_OPERATIONS_MANAGER" },
            new UserRole { RoleId = SeedIds.SystemAdministratorRole, RoleName = "SYSTEM_ADMINISTRATOR" });
        var seedTime = new DateTime(2026, 10, 4, 0, 0, 0, DateTimeKind.Utc);
        m.Entity<Policy>().HasData(new Policy { PolicyId = SeedIds.InitialPolicy, Version = 1, Status = "ACTIVE", EffectiveFrom = seedTime, DepositTimeoutHours = 1, ReservationVisitStartDay = 1, ReservationVisitEndDay = 5, MonthlyPaymentDueDay = 5, OverdueStartDay = 6, LateFeeDivisorDays = 31, EarlyReturnWaiveFeeUntilDay = 5, CreatedAt = seedTime });
        var names = new[] { "LOCK_DAMAGE", "DOOR_DAMAGE", "WALL_DAMAGE", "FLOOR_DAMAGE", "WATER_DAMAGE", "OTHER" };
        for (var i = 0; i < names.Length; i++) m.Entity<DamageType>().HasData(new DamageType { DamageTypeId = Guid.Parse($"30000000-0000-0000-0000-{i + 1:000000000000}"), Name = names[i], Status = "ACTIVE" });
        // ExtraFeeType names are authoritative, but DefaultAmount values are not. Keep that
        // deployment-data boundary explicit instead of inventing monetary seed values.
    }

    private static PropertyBuilder<string> Code(PropertyBuilder<string> p) => p.HasColumnType("varchar(50)").IsRequired();
    private static PropertyBuilder<string> Name(PropertyBuilder<string> p) => p.HasMaxLength(150).IsRequired();
    private static PropertyBuilder<decimal> Amount(PropertyBuilder<decimal> p) => p.HasColumnType(Money);
    private static PropertyBuilder<decimal?> Amount(PropertyBuilder<decimal?> p) => p.HasColumnType(Money);
    private static PropertyBuilder<DateTime> Utc(PropertyBuilder<DateTime> p) => p.HasColumnType(Timestamp);
    private static PropertyBuilder<DateTime?> Utc(PropertyBuilder<DateTime?> p) => p.HasColumnType(Timestamp);
}
