namespace Frms.DataAccess.Persistence.Entities;

public sealed class UserRole { public Guid RoleId { get; set; } public required string RoleName { get; set; } public string? Description { get; set; } }
public sealed class UserAccount { public Guid UserAccountId { get; set; } public Guid RoleId { get; set; } public required string Email { get; set; } public required string PhoneNumber { get; set; } public required string PasswordHash { get; set; } public required string Status { get; set; } public DateTime? EmailVerifiedAt { get; set; } public DateTime CreatedAt { get; set; } }
public sealed class Customer { public Guid CustomerId { get; set; } public Guid UserAccountId { get; set; } public required string FullName { get; set; } public string? Address { get; set; } public string? Cccd { get; set; } }
public sealed class Employee { public Guid EmployeeId { get; set; } public Guid UserAccountId { get; set; } public Guid? FacilityId { get; set; } public required string FullName { get; set; } }
public sealed class Facility { public Guid FacilityId { get; set; } public required string Name { get; set; } public required string Address { get; set; } public string? ContactInfo { get; set; } public string? Description { get; set; } public required string Status { get; set; } }
public sealed class UnitType { public Guid UnitTypeId { get; set; } public required string Name { get; set; } public required string Mode { get; set; } public required string Size { get; set; } public decimal RentalPrice { get; set; } public string? Description { get; set; } }
public sealed class StorageUnit { public Guid StorageUnitId { get; set; } public Guid FacilityId { get; set; } public Guid UnitTypeId { get; set; } public required string UnitCode { get; set; } public string? LocationInfo { get; set; } public required string Status { get; set; } }
public sealed class Reservation { public Guid ReservationId { get; set; } public Guid CustomerId { get; set; } public Guid FacilityId { get; set; } public Guid UnitTypeId { get; set; } public Guid PolicyId { get; set; } public DateOnly StartMonth { get; set; } public DateOnly EndMonth { get; set; } public decimal LockedRentalPrice { get; set; } public decimal DepositAmount { get; set; } public required string Status { get; set; } public DateTime CreatedAt { get; set; } }
public sealed class Visit { public Guid VisitId { get; set; } public Guid EntityId { get; set; } public Guid? EmployeeId { get; set; } public required string VisitType { get; set; } public DateOnly VisitDate { get; set; } public DateTime? ActualReturnDate { get; set; } public required string Status { get; set; } }
public sealed class Contract { public Guid ContractId { get; set; } public Guid ReservationId { get; set; } public Guid CustomerId { get; set; } public Guid FacilityId { get; set; } public Guid StorageUnitId { get; set; } public Guid PolicyId { get; set; } public Guid? DiscountId { get; set; } public DateOnly StartMonth { get; set; } public DateOnly EndMonth { get; set; } public required string Status { get; set; } }
public sealed class ContractExtension { public Guid ContractExtensionId { get; set; } public Guid ContractId { get; set; } public DateOnly OldEndMonth { get; set; } public DateOnly NewEndMonth { get; set; } public decimal AppliedMonthlyPrice { get; set; } public DateTime CreatedAt { get; set; } }
public sealed class Invoice { public Guid InvoiceId { get; set; } public Guid EntityId { get; set; } public required string InvoiceType { get; set; } public DateOnly? BillingMonth { get; set; } public decimal BaseAmount { get; set; } public Guid? DiscountId { get; set; } public decimal DiscountAmount { get; set; } public decimal AmountDue { get; set; } public DateTime DueDate { get; set; } public required string Status { get; set; } public DateTime? PaidAt { get; set; } public DateTime CreatedAt { get; set; } }
public sealed class Payment
{
    public Guid PaymentId { get; set; }
    public Guid InvoiceId { get; set; }
    public Guid IdempotencyKey { get; set; }
    public long? ProviderOrderCode { get; set; }
    public decimal Amount { get; set; }
    public required string PaymentMethod { get; set; }
    public string? TransactionCode { get; set; }
    [System.Text.Json.Serialization.JsonIgnore]
    public string? PaymentUrl { get; set; }
    public DateTime? PaymentUrlExpiresAt { get; set; }
    public required string Status { get; set; }
    public DateTime? PaidAt { get; set; }
    public DateTime CreatedAt { get; set; }
}
public sealed class LateFee { public Guid LateFeeId { get; set; } public Guid InvoiceId { get; set; } public int OverdueDays { get; set; } public decimal Amount { get; set; } public DateTime CalculatedAt { get; set; } }
public sealed class Discount { public Guid DiscountId { get; set; } public Guid CustomerId { get; set; } public required string Name { get; set; } public decimal Percentage { get; set; } public required string Status { get; set; } public DateTime EffectiveFrom { get; set; } public DateTime? EffectiveTo { get; set; } }
public sealed class Policy { public Guid PolicyId { get; set; } public int Version { get; set; } public required string Status { get; set; } public DateTime EffectiveFrom { get; set; } public DateTime? EffectiveTo { get; set; } public int DepositTimeoutHours { get; set; } public int ReservationVisitStartDay { get; set; } public int ReservationVisitEndDay { get; set; } public int MonthlyPaymentDueDay { get; set; } public int OverdueStartDay { get; set; } public int LateFeeDivisorDays { get; set; } public int EarlyReturnWaiveFeeUntilDay { get; set; } public DateTime CreatedAt { get; set; } }
public sealed class SupportTicket { public Guid SupportTicketId { get; set; } public Guid ContractId { get; set; } public Guid CustomerId { get; set; } public Guid? AssignedEmployeeId { get; set; } public required string Category { get; set; } public required string Description { get; set; } public required string Status { get; set; } public string? ResultNote { get; set; } public DateTime CreatedAt { get; set; } public DateTime? CompletedAt { get; set; } }
public sealed class Inspection { public Guid InspectionId { get; set; } public Guid ContractId { get; set; } public Guid StorageUnitId { get; set; } public Guid? VisitId { get; set; } public Guid? EmployeeId { get; set; } public required string Status { get; set; } public string? ConditionNote { get; set; } public DateTime? CompletedAt { get; set; } }
public sealed class DamageType { public Guid DamageTypeId { get; set; } public required string Name { get; set; } public decimal? DefaultAmount { get; set; } public required string Status { get; set; } }
public sealed class DamageRecord { public Guid DamageRecordId { get; set; } public Guid InspectionId { get; set; } public Guid DamageTypeId { get; set; } public decimal DamageAmount { get; set; } public string? Note { get; set; } public required string Status { get; set; } public DateTime CreatedAt { get; set; } }
public sealed class InspectionEvidence { public Guid InspectionEvidenceId { get; set; } public Guid InspectionId { get; set; } public required byte[] FileData { get; set; } public required string EvidenceType { get; set; } public DateTime CreatedAt { get; set; } }
public sealed class ExtraFeeType { public Guid ExtraFeeTypeId { get; set; } public required string Name { get; set; } public decimal DefaultAmount { get; set; } public required string Status { get; set; } }
public sealed class ExtraFee { public Guid ExtraFeeId { get; set; } public Guid InspectionId { get; set; } public Guid ExtraFeeTypeId { get; set; } public decimal Amount { get; set; } public required string Reason { get; set; } public DateTime CreatedAt { get; set; } }
public sealed class DepositSettlement { public Guid DepositSettlementId { get; set; } public Guid ContractId { get; set; } public decimal TotalDeduction { get; set; } public decimal RefundAmount { get; set; } public decimal AdditionalAmountDue { get; set; } public required string Status { get; set; } public DateTime CalculatedAt { get; set; } }
public sealed class LoginHistory { public Guid LoginHistoryId { get; set; } public Guid UserAccountId { get; set; } public DateTime LoginAt { get; set; } public string? IpAddress { get; set; } public string? DeviceInfo { get; set; } public required string Status { get; set; } }
public sealed class AuditLog { public Guid AuditLogId { get; set; } public Guid? UserAccountId { get; set; } public required string Action { get; set; } public required string EntityType { get; set; } public Guid? EntityId { get; set; } public string? OldValue { get; set; } public string? NewValue { get; set; } public DateTime CreatedAt { get; set; } }
public sealed class NotificationLog { public Guid NotificationLogId { get; set; } public Guid UserAccountId { get; set; } public required string NotificationType { get; set; } public required string Content { get; set; } public required string Status { get; set; } public DateTime? SentAt { get; set; } public DateTime CreatedAt { get; set; } }
