<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Frms.Business\Frms.Business.csproj" />
    <ProjectReference Include="..\Frms.DataAccess\Frms.DataAccess.csproj" />
    <ProjectReference Include="..\Frms.Infrastructure\Frms.Infrastructure.csproj" />
  </ItemGroup>

</Project>
